replicaCount: 1

image:
  repository: anpauthuser.azurecr.io/http-echo-project:$BUILD_NUMBER
  pullPolicy: IfNotPresent

deployment:
  containerport: 80


service:
  type: ClusterIP
  port: 80
  targetport: 80

ingress:
  enabled: false
  className: ""
  port: 80
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Exact
