replicaCount: 1

image:
  repository: 
  pullPolicy: IfNotPresent

deployment:
  containerport: 80


service:
  type: ClusterIP
  port: 80
  targetport: 80

ingress:
  enabled: false
  className: ""
  port: 80
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Exact
