apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "http-echo-project-chart.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
          service:
            name: {{ include "http-echo-project-chart.fullname" . }}-svc
            port:
              number: {{ .Values.service.port }}
