apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo-project-chart.fullname" . }}
  labels:
    app: {{ include "http-echo-project-chart.name" . }} 
spec:
  selector:
    app: {{ include "http-echo-project-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
